// Generated by Wrangler
// After adding bindings to `wrangler.jsonc`, regenerate this interface via `npm run cf-typegen`
//
// NOTE (semantic review v1, issue #5): the `FLUX_TOKEN: string` field below is hand-added.
// Wrangler secrets are intentionally NOT declared in `wrangler.jsonc` (their value lives in
// `wrangler secret put`), so a clean `npm run cf-typegen` run on a fresh checkout will
// regenerate this file WITHOUT `FLUX_TOKEN` and the Worker source will fail type-check until
// someone re-adds it. If `cf-typegen` is rerun, restore the `FLUX_TOKEN: string` line by hand
// (or rely solely on the exported `Env` interface in `src/index.ts`, which is the source of
// truth for the request handler — see `satisfies ExportedHandler<Env>` in that file).
interface Env {
	AI: Ai;
	FLUX_TOKEN: string;
}
